

cassandra:
  image:
    repository: cdliotprototype/cdl-refit-cassandra
    tag: latest
  cluster:
    replicaCount: 4
    seedCount: 4
  persistence:
    enabled: false
    # storageClass: glusterfs
  dbUser:
    user: cassandra
    password: cassandra

  nodeSelector: 
    coredns: enabled
  resources:
    limits:
      memory: "10000Mi"
    requests:
      memory: "3000Mi"
redis: 
  usePassword: true
  password: redis
  master: 
    nodeSelector: 
      coredns: enabled
    persistence:
      enabled: false
      # storageClass: glusterfs
  slave: 
    nodeSelector: 
      coredns: enabled
    persistence:
      enabled: false
      # storageClass: glusterfs

  cluster: 
    slaveCount: 2
  metrics:
    enabled: false

  resources:
    limits:
      memory: "10000Mi"
    requests:
      memory: "3000Mi"

grafana: 
  nodeSelector:
    coredns: enabled
  persistence:
    enabled: false
  env:
    GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource,simpod-json-datasource
  plugins:
    - name:
      value: grafana-simple-json-datasource

flink: 
  flinkVersion: 1.10.1
  scalaVersion: 2.11
  nodeSelector:
        coredns: enabled
  jobManager: 
    limits: 
      memory: "5000Mi"
    requests: 
      memory: "2000Mi"
  taskManager: 
    replicas: 1
    limits: 
      memory: "5000Mi"
    requests: 
      memory: "2000Mi"
pulsar:
  pulsarVersion: 2.6.0
  nodeSelector:
    coredns: enabled
  resources: 
    limits: 
      memory: "10000Mi"
    requests: 
      memory: "3000Mi"

refit: 
  version: latest
  encryptionKey: __generated__
  nodeSelector:
    coredns: enabled
  integrations:
    replicas: 1
    resources:
      limits:
        memory: "2000Mi"
      requests:
        memory: "500Mi"
