name: Releases

on:
  release:
    types: [published]

jobs:
  inference:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Compile Source Code
        run: sbt inference/assembly
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cdliotprototype/cdl-refit-inference
          tag_with_ref: true
          path: inference

  ingestion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Compile Source Code
        run: sbt ingestion/assembly
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cdliotprototype/cdl-refit-ingestion
          tag_with_ref: true
          path: ingestion

  integrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Compile Source Code
        run: sbt integrations/assembly
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cdliotprototype/cdl-refit-integrations
          tag_with_ref: true
          path: integrations

  cassandra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cdliotprototype/cdl-refit-cassandra
          tag_with_ref: true
          path: db/src/main/cql

  notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cdliotprototype/cdl-refit-notebook
          tag_with_ref: true
          path: training

  flink:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cdliotprototype/cdl-refit-flink
          tag_with_ref: true
          path: resources/flink